# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_page_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default='First', max_length=200),
            preserve_default=False,
        ),
    ]
